### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\Users\USUARIO\.vscode\extensions\lvboda.vscode-img-fast-1.0.3\out\records.json'

### ISSUE THREAD

**Issue by gyutaro12** [lvboda/vscode-img-fast#18]
porque me sale error si quiero hacer un fondo de la página. ayudaaaaa

**Comment by lvboda** [comment]
Thanks for reporting this. This issue is a duplicate of #13. Please follow the original issue for updates.
