### ISSUE TITLE
TypeError: Cannot read properties of undefined  reading 'length' 

### ISSUE THREAD

**Issue by CopperLee16** [lvboda/vscode-img-fast#6]
上传图片文件失败，右下角显示错误 `TypeError: Cannot read properties of undefined  reading 'length' `

**Comment by lvboda** [comment]
控制台截屏给我看一下错误

**Comment by CopperLee16** [comment]
> 控制台截屏给我看一下错误

已经解决了 是我有配置填错了 谢谢
